### ISSUE TITLE
Lowercase the method names

### ISSUE THREAD

**Issue by caseywoolley** [shystruk/custom-event-js#4]
This would fit standard js naming conventions better:

CustomEvent.DISPATCH => dispatch
CustomEvent.ON => on
CustomEvent.OFF => off

**Comment by shystruk** [comment]
Good point. Thanks
uppercase more readable for me :)

**Comment by shystruk** [comment]
let's see what community think about that :)
https://twitter.com/shystrukk/status/1120765695959003136

**Comment by shystruk** [comment]
changes in v.1.0
